<?php
declare(strict_types=1);

use Caiofior\Core\ProfileValidation;
use PHPUnit\Framework\TestCase;
use DI\ContainerBuilder;
use Slim\Factory\AppFactory;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-21 at 11:54:01.
 */
class RecoverMailTest extends TestCase
{
    
    public function testProfile() {

        $containerBuilder = new ContainerBuilder();
        // Add DI container definitions
        $containerBuilder->addDefinitions(__DIR__ . '/../config/container.php');
        $container = $containerBuilder->build(); 
        $entityManager = $container->get('entity_manager');
        $login = $entityManager->find('\Caiofior\Core\model\Login','caiofior');
        
        $profileValidation = new ProfileValidation($container);

        $profileValidation->sentRecoverMail($login);
    }

}
