<?php
declare(strict_types=1);
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-21 at 11:54:01.
 */
class CalendarTest extends TestCase
{
    /**
     * @var Caiofior\CatholicLiturgical\Calendar
     */
    protected $object;

    public function testGetCurrentDay() {
       $this->object = new \Caiofior\CatholicLiturgical\Calendar('today');
       $dateTime = $this->object->getDateTime();
       $this->assertTrue (is_string($dateTime->getTime()) && $dateTime->getTime() != '');
       $this->assertTrue (is_numeric($dateTime->getWeekTimeNumber()) && $dateTime->getWeekTimeNumber() > 0);
       $this->assertTrue (is_numeric($dateTime->getWeekPsalterNumber()) && $dateTime->getWeekPsalterNumber() > 0);
       $this->assertTrue (is_string($this->object->getLithurgicYear()) && $this->object->getLithurgicYear() != '');
       $this->expectException(
          Exception::class
        );
       $dateTime = new \Caiofior\CatholicLiturgical\Calendar('dsfgsdg');
    }

}
